import { AboutSlint, VerticalBox, Palette } from "std-widgets.slint";

export component AboutTab {
    in property <string> version: "1.0.2";
    callback open_repository();
    VerticalLayout {
        alignment: center;
        spacing: 1rem;
        Text {
            horizontal-alignment: center;
            text: "Sanctuary Seeder v" + version + " by Minavoii\n";
            font-size: 1.5rem;
            font-weight: 400;
        }

        TouchArea {
            Text {
                horizontal-alignment: center;
                text: "https://github.com/Minavoii/Sanctuary-Seeder";
                font-size: 1.2rem;
                color: Palette.accent-background;
            }

            clicked => {
                open_repository();
            }
        }

        VerticalBox {
            padding-top: 3.5rem;
            AboutSlint {
                height: 10rem;
            }
        }
    }
}
