CREATE TABLE IF NOT EXISTS "Bravery" (
    "Id" INTEGER NOT NULL,
    "Familiar" INTEGER,
    "Start1" INTEGER,
    "Start2" INTEGER,
    "Swimming" INTEGER,
    "Bex" INTEGER,
    "Cryomancer" INTEGER,
    "CryomancerRequired" INTEGER,
    "EndOfTime1" INTEGER,
    "EndOfTime2" INTEGER,
    "EndOfTime3" INTEGER,
    "Army1" INTEGER,
    "Army2" INTEGER,
    "Army3" INTEGER,
    "Army4" INTEGER,
    "Army5" INTEGER,
    "Army6" INTEGER,
    "Army7" INTEGER,
    "MountainPath" INTEGER,
    "BlueCaves" INTEGER,
    "StrongholdDungeon" INTEGER,
    "AncientWoods" INTEGER,
    "SnowyPeaks" INTEGER,
    "SunPalace" INTEGER,
    "HorizonBeach" INTEGER,
    "MagmaChamber" INTEGER,
    "MysticalWorkshop" INTEGER,
    "Underworld" INTEGER,
    "AbandonedTower" INTEGER,
    "BlobBurg" INTEGER,
    "ForgottenWorld" INTEGER,
    PRIMARY KEY("Id")
)